// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rubvvbojjfgkblcdendv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1YnZ2Ym9qamZna2JsY2RlbmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NzIwMzIsImV4cCI6MjA2NjU0ODAzMn0.3niE9C9_FbtAgjgCBwByjMcGCp0NctSqT7exHkyFLPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);